package br.com.usinasantafe.cmm.common.utils

const val BASE_URL = "https://www.usinasantafe.com.br/cmmdev/view/"
const val BASE_SHARE_PREFERENCES = "cmm"
const val BASE_DB = "cmm.db"
const val VERSION_DB = 1

const val BASE_SHARE_PREFERENCES_TABLE_CONFIG = "config"
const val BASE_SHARE_PREFERENCES_TABLE_BOLETIM_MM = "boletim_mm"
const val BASE_SHARE_PREFERENCES_TABLE_BOLETIM_FERT = "boletim_fert"
const val BASE_SHARE_PREFERENCES_TABLE_APONT_MM = "apont_mm"
const val BASE_SHARE_PREFERENCES_TABLE_APONT_FERT = "apont_fert"
const val BASE_SHARE_PREFERENCES_TABLE_LIST_IMPLEMENTO = "list_implemento"

const val TB_ATIVIDADE = "tb_atividade"
const val TB_BOCAL = "tb_bocal"
const val TB_COMPONENTE = "tb_componente"
const val TB_EQUIP = "tb_equip"
const val TB_EQUIP_SEG = "tb_equip_seg"
const val TB_FRENTE = "tb_frente"
const val TB_FUNC = "tb_func"
const val TB_ITEM_CHECKLIST = "tb_item_checklist"
const val TB_ITEM_OS_MECAN = "tb_item_os_mecan"
const val TB_LEIRA = "tb_leira"
const val TB_OPER_MOTOMEC = "tb_oper_motomec"
const val TB_OS = "tb_os"
const val TB_PARADA = "tb_parada"
const val TB_PNEU = "tb_pneu"
const val TB_PRESSAO_BOCAL = "tb_pressao_bocal"
const val TB_PRODUTO = "tb_produto"
const val TB_PROPRIEDADE = "tb_propriedade"
const val TB_R_ATIV_PARADA = "tb_r_ativ_parada"
const val TB_R_EQUIP_ATIV = "tb_r_equip_ativ"
const val TB_R_EQUIP_PNEU = "tb_r_equip_pneu"
const val TB_R_FUNCAO_ATIV_PARADA = "tb_r_funcao_ativ_parada"
const val TB_R_OS_ATIV = "tb_r_os_ativ"
const val TB_SERVICO = "tb_servico"
const val TB_TURNO = "tb_turno"

const val TB_APONT_FERT = "tb_apont_fert"
const val TB_APONT_MECAN = "tb_apont_mecan"
const val TB_APONT_MM = "tb_apont_mm"
const val TB_BOLETIM_FERT = "tb_boletim_fert"
const val TB_BOLETIM_MM = "tb_boletim_mm"
const val TB_CABEC_CHECK_LIST = "tb_cabec_check_list"
const val TB_RESP_ITEM_CHECK_LIST = "tb_resp_item_check_list"

const val WEB_FIELD_NRO_EQUIP = "nroEquip"
const val WEB_FIELD_NRO_OS = "nroOS"

const val WEB_FIND_EQUIP = "find-equip.php"
const val WEB_FIND_OS = "find-os.php"
const val WEB_FIND_R_OS_ATIV = "find-rosativ.php"
const val WEB_FIND_R_EQUIP_ATIV = "find-requipativ.php"
const val WEB_FIND_R_EQUIP_PNEU = "find-requippneu.php"

const val WEB_ALL_ATIVIDADE = "atividade.php"
const val WEB_ALL_BOCAL = "bocal.php"
const val WEB_ALL_COMPONENTE = "componente.php"
const val WEB_ALL_EQUIP_SEG = "equipseg.php"
const val WEB_ALL_FRENTE = "frente.php"
const val WEB_ALL_FUNC = "func.php"
const val WEB_ALL_ITEM_CHECKLIST = "itemchecklist.php"
const val WEB_ALL_ITEM_OS_MECAN = "itemosmecan.php"
const val WEB_ALL_LEIRA = "leira.php"
const val WEB_ALL_OPER_MOTOMEC = "opermotomec.php"
const val WEB_ALL_OS = "os.php"
const val WEB_ALL_PARADA = "parada.php"
const val WEB_ALL_PNEU = "pneu.php"
const val WEB_ALL_PRESSAO_BOCAL = "pressaobocal.php"
const val WEB_ALL_PRODUTO = "produto.php"
const val WEB_ALL_PROPRIEDADE = "propriedade.php"
const val WEB_ALL_R_ATIV_PARADA = "rativparada.php"
const val WEB_ALL_R_FUNCAO_ATIV_PARADA = "rfuncaoativparada.php"
const val WEB_ALL_R_OS_ATIV = "rosativ.php"
const val WEB_ALL_SERVICO = "servico.php"
const val WEB_ALL_TURNO = "turno.php"

const val WEB_SAVE_CHECK_LIST = "save-checklist.php"
const val WEB_SAVE_FERTIRRIGACAO = "save-fertirrigacao.php"
const val WEB_SAVE_MOTOMEC = "save-motomec.php"

const val WEB_UPDATE_APP = "update-app.php"

const val WEB_RETURN_CLEAR_EQUIP = "Equipamento Inexistente!"
const val WEB_RETURN_CLEAR_OS = "OS Inexistente!"

const val TEXT_SUCESS_UPDATE = "Atualização realizada com Sucesso!"
const val TEXT_CLEAR_TB = "Limpando Dados da Tabela "
const val TEXT_RECEIVE_WS_TB = "Recebendo Dados da Tabela "
const val TEXT_SAVE_DATA_TB = "Salvandos Dados da Tabela "
const val TEXT_FINISH_UPDATE = "Termino de Atualização"
